import http from 'node:http';
import path from 'path';
import { fileURLToPath } from 'url';
import { spawn } from 'node:child_process';
import { DatabaseSync } from 'node:sqlite';
import crypto from 'node:crypto';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const PORT=Number(process.env.PORT||3000),BACKEND_PORT=Number(process.env.BACKEND_PORT||3001),DB_PATH=process.env.DB_PATH||path.join(__dirname,'data.sqlite'),SECRET=process.env.JWT_SECRET||'ULGURJI_CHANGE_SECRET';
const db=new DatabaseSync(DB_PATH),q=s=>db.prepare(s),now=()=>new Date().toISOString(),b64=s=>Buffer.from(s).toString('base64url'),ub=s=>Buffer.from(s,'base64url').toString();
db.exec(`CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT DEFAULT '',work_date TEXT NOT NULL,employee_id INTEGER NOT NULL,created_by INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'ASSIGNED',result_text TEXT DEFAULT '',completed_at TEXT,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS task_files(id INTEGER PRIMARY KEY AUTOINCREMENT,task_id INTEGER NOT NULL,uploaded_by INTEGER NOT NULL,filename TEXT NOT NULL,mime TEXT DEFAULT 'application/octet-stream',data BLOB NOT NULL,uploaded_at TEXT NOT NULL);`);
function verify(t){const a=String(t||'').split('.');if(a.length!==3)throw Error('AUTH_INVALID');const e=b64(crypto.createHmac('sha256',SECRET).update(a[0]+'.'+a[1]).digest());if(e.length!==a[2].length||!crypto.timingSafeEqual(Buffer.from(e),Buffer.from(a[2])))throw Error('AUTH_INVALID');const p=JSON.parse(ub(a[1]));if(!p.exp||p.exp<Date.now()/1000)throw Error('AUTH_INVALID');return p}
function auth(req,res,admin=false){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw Error('AUTH_INVALID');const u=verify(h.slice(7));if(admin&&u.role!=='admin')throw Error('ADMIN_ONLY');return u}catch(e){res.writeHead(e.message==='ADMIN_ONLY'?403:401,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'});res.end(JSON.stringify({error:e.message==='ADMIN_ONLY'?'ADMIN_ONLY':'AUTH_INVALID'}));return null}}
function send(res,c,d,t='application/json',h={}){res.writeHead(c,{'Content-Type':t,'Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Authorization, Content-Type',...h});res.end(t.includes('json')?JSON.stringify(d):d)}
async function body(req,max=10e6){return await new Promise((ok,no)=>{const a=[];let n=0;req.on('data',c=>{n+=c.length;if(n>max){no(Error('BODY_TOO_LARGE'));req.destroy();return}a.push(c)});req.on('end',()=>ok(Buffer.concat(a)));req.on('error',no)})}
async function json(req){return JSON.parse((await body(req)).toString('utf8')||'{}')}
const dateOk=x=>/^\d{4}-\d{2}-\d{2}$/.test(String(x||''));const safe=s=>path.basename(String(s||'photo')).replace(/[^\p{L}\p{N}._ -]/gu,'_').slice(0,120)||'photo';
function files(id){return q('SELECT id,task_id,filename,mime,LENGTH(data) size,uploaded_at FROM task_files WHERE task_id=? ORDER BY id').all(id)}
function task(id){return q('SELECT t.*,u.employee_name,u.region,u.district FROM tasks t LEFT JOIN users u ON u.id=t.employee_id WHERE t.id=?').get(id)}
function list(u,d){const day=dateOk(d)?d:new Date().toISOString().slice(0,10),where=u.role==='admin'?'t.work_date=?':'t.employee_id=? AND t.work_date=?',args=u.role==='admin'?[day]:[u.id,day];return q(`SELECT t.*,u.employee_name,u.region,u.district,(SELECT COUNT(*) FROM task_files f WHERE f.task_id=t.id) files_count FROM tasks t LEFT JOIN users u ON u.id=t.employee_id WHERE ${where} ORDER BY CASE t.status WHEN 'NOT_COMPLETED' THEN 0 WHEN 'IN_PROGRESS' THEN 1 WHEN 'ASSIGNED' THEN 2 ELSE 3 END,t.id DESC`).all(...args)}
async function tasks(req,res,url){if(!url.startsWith('/api/tasks'))return false;try{
if(req.method==='GET'&&url==='/api/tasks'){const u=auth(req,res);if(!u)return true;const d=new URL(req.url,'http://local').searchParams.get('date');send(res,200,{date:d,items:list(u,d)});return true}
if(req.method==='POST'&&url==='/api/tasks'){const u=auth(req,res,true);if(!u)return true;const b=await json(req),title=String(b.title||'').trim(),description=String(b.description||''),day=dateOk(b.work_date)?b.work_date:new Date().toISOString().slice(0,10),eid=Number(b.employee_id);if(!title||!eid){send(res,400,{error:'TASK_REQUIRED'});return true}if(!q("SELECT id FROM users WHERE id=? AND role='employee' AND active=1").get(eid)){send(res,404,{error:'EMPLOYEE_NOT_FOUND'});return true}const r=q('INSERT INTO tasks(title,description,work_date,employee_id,created_by,status,created_at) VALUES(?,?,?,?,?,?,?)').run(title,description,day,eid,u.id,'ASSIGNED',now()),id=Number(r.lastInsertRowid);for(const f of Array.isArray(b.attachments)?b.attachments:[]){const m=String(f.data||'').match(/^data:([^;]+);base64,(.+)$/s);if(!m)continue;const buf=Buffer.from(m[2],'base64');if(buf.length>6e6)continue;q('INSERT INTO task_files(task_id,uploaded_by,filename,mime,data,uploaded_at) VALUES(?,?,?,?,?,?)').run(id,u.id,safe(f.name),String(f.type||m[1]),buf,now())}send(res,200,{ok:true,task_id:id});return true}
const m=url.match(/^\/api\/tasks\/(\d+)(?:\/files)?$/);if(!m){send(res,404,{error:'NOT_FOUND'});return true}const id=Number(m[1]),u=auth(req,res);if(!u)return true;const t=task(id);if(!t){send(res,404,{error:'TASK_NOT_FOUND'});return true}if(u.role!=='admin'&&t.employee_id!==u.id){send(res,403,{error:'TASK_FORBIDDEN'});return true}
if(req.method==='GET'&&!url.endsWith('/files')){send(res,200,{task:t,files:files(id)});return true}
if(req.method==='GET'&&url.endsWith('/files')){const fid=Number(new URL(req.url,'http://local').searchParams.get('file')),f=q('SELECT * FROM task_files WHERE id=? AND task_id=?').get(fid,id);if(!f){send(res,404,{error:'FILE_NOT_FOUND'});return true}send(res,200,f.data,f.mime,{'Content-Disposition':`inline; filename="${safe(f.filename)}"`});return true}
if(req.method==='POST'){const b=await json(req),status=String(b.status||'').toUpperCase(),allowed=['ASSIGNED','IN_PROGRESS','COMPLETED','NOT_COMPLETED'];if(!allowed.includes(status)){send(res,400,{error:'TASK_STATUS_INVALID'});return true}if(u.role!=='admin'&&status==='ASSIGNED'){send(res,403,{error:'TASK_FORBIDDEN'});return true}const result=String(b.result_text||'');q('UPDATE tasks SET status=?,result_text=?,completed_at=? WHERE id=?').run(status,result,status==='COMPLETED'?now():null,id);for(const f of Array.isArray(b.attachments)?b.attachments:[]){const mm=String(f.data||'').match(/^data:([^;]+);base64,(.+)$/s);if(!mm)continue;const buf=Buffer.from(mm[2],'base64');if(buf.length>6e6)continue;q('INSERT INTO task_files(task_id,uploaded_by,filename,mime,data,uploaded_at) VALUES(?,?,?,?,?,?)').run(id,u.id,safe(f.name),String(f.type||mm[1]),buf,now())}send(res,200,{ok:true});return true}
send(res,405,{error:'METHOD_NOT_ALLOWED'});return true;
}catch(e){send(res,500,{error:'TASK_SERVER_ERROR',message:String(e.message||e)});return true}}
const child=spawn(process.execPath,[path.join(__dirname,'server.js')],{env:{...process.env,PORT:String(BACKEND_PORT)},stdio:'inherit'});child.on('exit',c=>{if(c&&c!==0)console.error('BACKEND_EXIT',c)});
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'});return res.end()}const u=new URL(req.url,'http://local');if(await tasks(req,res,u.pathname))return;const opts={hostname:'127.0.0.1',port:BACKEND_PORT,path:req.url,method:req.method,headers:{...req.headers,host:`127.0.0.1:${BACKEND_PORT}`}};const pr=http.request(opts,rr=>{if((req.url==='/'||u.pathname.endsWith('.html'))&&String(rr.headers['content-type']||'').includes('text/html')){const chunks=[];rr.on('data',c=>chunks.push(c));rr.on('end',()=>{let html=Buffer.concat(chunks).toString('utf8');if(!html.includes('/tasks-v2.js'))html=html.replace('</body>','<script src="/tasks-v2.js?v=1"></script><script src="/final-ui.js?v=1"></script></body>');else if(!html.includes('/final-ui.js'))html=html.replace('</body>','<script src="/final-ui.js?v=1"></script></body>');const h={...rr.headers,'content-length':Buffer.byteLength(html)};delete h['transfer-encoding'];res.writeHead(rr.statusCode||500,h);res.end(html)})}else{res.writeHead(rr.statusCode||500,rr.headers);rr.pipe(res)}});pr.on('error',e=>{if(!res.headersSent)send(res,502,{error:'BACKEND_UNAVAILABLE',message:e.message})});req.pipe(pr)});server.listen(PORT,'0.0.0.0',()=>console.log(`ULGURJI_GATEWAY_READY port=${PORT} backend=${BACKEND_PORT}`));
process.on('SIGTERM',()=>{child.kill('SIGTERM');server.close(()=>process.exit(0))});process.on('SIGINT',()=>{child.kill('SIGINT');server.close(()=>process.exit(0))});
