import http from 'node:http';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawn} from 'node:child_process';
import {handleEmployeeApi} from './employee-entry-api.js';
import {handleManagerEmployeeUsers} from './manager-employee-users-v1.js';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const PORT=Number(process.env.PORT||3000), INNER_PORT=Number(process.env.INNER_PORT||3001), INNER_BACKEND=Number(process.env.BACKEND_PORT||3002);
const UI_SCRIPTS=['/tasks-v3.js?v=6','/management-v9.js?v=3','/map-close-v9.js?v=2','/final-v10.js?v=2','/employee-panel-v1.js?v=2','/final-overrides.js?v=2','/completion-guard-v1.js?v=1','/field-survey-v1.js?v=1','/login-password-eye-v1.js?v=1','/manager-employee-users-ui-v1.js?v=1'];
const child=spawn(process.execPath,[path.join(__dirname,'boot.js')],{env:{...process.env,PORT:String(INNER_PORT),BACKEND_PORT:String(INNER_BACKEND)},stdio:'inherit'});
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,'http://local');if(u.pathname.startsWith('/api/manager-employee-users')){const handled=await handleManagerEmployeeUsers(req,res,u.pathname);if(handled)return}if(u.pathname.startsWith('/api/employee-')||u.pathname.startsWith('/api/manager-employee-')){const handled=await handleEmployeeApi(req,res,u.pathname);if(handled)return}const opts={hostname:'127.0.0.1',port:INNER_PORT,path:req.url,method:req.method,headers:{...req.headers,host:`127.0.0.1:${INNER_PORT}`}};const pr=http.request(opts,rr=>{if((req.url==='/'||u.pathname.endsWith('.html'))&&String(rr.headers['content-type']||'').includes('text/html')){const chunks=[];rr.on('data',c=>chunks.push(c));rr.on('end',()=>{let html=Buffer.concat(chunks).toString('utf8');for(const src of UI_SCRIPTS){const bare=src.split('?')[0];if(!html.includes(bare))html=html.replace('</body>',`<script src="${src}"></script></body>`)}const h={...rr.headers,'content-length':Buffer.byteLength(html)};delete h['transfer-encoding'];res.writeHead(rr.statusCode||500,h);res.end(html)})}else{res.writeHead(rr.statusCode||500,rr.headers);rr.pipe(res)}});pr.on('error',e=>{if(!res.headersSent){res.writeHead(502,{'Content-Type':'application/json'});res.end(JSON.stringify({error:'GATEWAY_UNAVAILABLE',message:e.message}))}});req.pipe(pr)});
server.listen(PORT,'0.0.0.0',()=>console.log(`ULGURJI_GATEWAY_V4_READY port=${PORT}`));
process.on('SIGTERM',()=>{child.kill('SIGTERM');server.close(()=>process.exit(0))});process.on('SIGINT',()=>{child.kill('SIGINT');server.close(()=>process.exit(0))});
