import http from 'node:http';
import path from 'path';
import {fileURLToPath} from 'url';
import {spawn} from 'node:child_process';
import {handleEmployeeApi} from './employee-entry-api.js';
import {handleManagerEmployeeUsers} from './manager-employee-users-v1.js';
import {handleLocationApproval} from './location-approval-api.js';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const PORT=Number(process.env.PORT||3000), INNER_PORT=Number(process.env.INNER_PORT||3001), INNER_BACKEND=Number(process.env.BACKEND_PORT||3002);
const UI_SCRIPTS=['/tasks-v3.js?v=8','/management-v9.js?v=5','/map-close-v9.js?v=4','/final-v10.js?v=5','/employee-panel-v1.js?v=4','/final-overrides.js?v=4','/employee-mobile-ui-v1.js?v=3','/employee-panel-v2-ui.js?v=2','/employee-panel-v3-ui.js?v=2','/employee-panel-v4-fix.js?v=3','/enhance.js?v=10','/daily-view-fix-v1.js?v=1','/final-control-v1.js?v=1','/location-approval-ui-v1.js?v=1','/employee-entry-final-fix-v1.js?v=2'];
const child=spawn(process.execPath,[path.join(__dirname,'boot.js')],{env:{...process.env,PORT:String(INNER_PORT),BACKEND_PORT:String(INNER_BACKEND)},stdio:'inherit'});
child.on('exit',code=>{console.error(`BACKEND_EXIT:${code??'unknown'}`);if(code!==0)process.exitCode=code||1});
function proxy(req,res,pathName){return new Promise(resolve=>{const opts={hostname:'127.0.0.1',port:INNER_PORT,path:pathName,method:req.method,headers:{...req.headers,host:`127.0.0.1:${INNER_PORT}`}};const pr=http.request(opts,rr=>{if((req.url==='/'||pathName.endsWith('.html'))&&String(rr.headers['content-type']||'').includes('text/html')){const chunks=[];rr.on('data',c=>chunks.push(c));rr.on('end',()=>{let html=Buffer.concat(chunks).toString('utf8');for(const src of UI_SCRIPTS){const bare=src.split('?')[0];if(!html.includes(bare))html=html.replace('</body>',`<script src=\"${src}\"></script></body>`)}const h={...rr.headers,'content-length':Buffer.byteLength(html),'cache-control':'no-store, no-cache, must-revalidate, max-age=0','pragma':'no-cache'};delete h['transfer-encoding'];res.writeHead(rr.statusCode||500,h);res.end(html);resolve()})}else{res.writeHead(rr.statusCode||500,rr.headers);rr.pipe(res);rr.on('end',resolve)}});pr.on('error',e=>{if(!res.headersSent){res.writeHead(502,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify({error:'GATEWAY_UNAVAILABLE',message:e.message}))}resolve()});req.pipe(pr)});}
async function correctedMonthly(req,res,u){const m=u.searchParams.get('month');if(!/^\d{4}-\d{2}$/.test(String(m||''))){return proxy(req,res,req.url)};const days=new Date(Number(m.slice(0,4)),Number(m.slice(5,7)),0).getDate();const rows=new Map();for(let d=1;d<=days;d++){const date=`${m}-${String(d).padStart(2,'0')}`;const data=await new Promise(resolve=>{const opts={hostname:'127.0.0.1',port:INNER_PORT,path:`/api/report?date=${date}`,method:'GET',headers:{authorization:req.headers.authorization||'',host:`127.0.0.1:${INNER_PORT}`}};const pr=http.request(opts,rr=>{const chunks=[];rr.on('data',c=>chunks.push(c));rr.on('end',()=>{try{resolve(JSON.parse(Buffer.concat(chunks).toString('utf8')))}catch{resolve({rows:[]})}})});pr.on('error',()=>resolve({rows:[]}));pr.end()});for(const r of Array.isArray(data.rows)?data.rows:[]){let x=rows.get(r.employee_id);if(!x){x={employee_id:r.employee_id,employee:r.employee,region:r.region,district:r.district,planned:0,visited:0,valid:0,suspicious:0,not_visited:0}}x.planned+=Number(r.planned||0);x.visited+=Number(r.visited||0);x.valid+=Math.max(0,Number(r.visited||0)-Number(r.suspicious||0));x.suspicious+=Number(r.suspicious||0);x.not_visited+=Number(r.not_visited??Math.max(0,Number(r.planned||0)-Number(r.visited||0)));rows.set(r.employee_id,x)}}const out=[...rows.values()].map(r=>({...r,completion:r.planned?Math.round(r.visited/r.planned*1000)/10:0}));sendJson(res,200,{month:m,rows:out,summary:{employees:out.length,planned:out.reduce((s,r)=>s+r.planned,0),visited:out.reduce((s,r)=>s+r.visited,0),valid:out.reduce((s,r)=>s+r.valid,0),suspicious:out.reduce((s,r)=>s+r.suspicious,0),not_visited:out.reduce((s,r)=>s+r.not_visited,0)}})}
function sendJson(res,status,data){const body=JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store, no-cache, must-revalidate','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Allow-Methods':'GET, POST, PUT, PATCH, DELETE, OPTIONS','Content-Length':Buffer.byteLength(body)});res.end(body)}
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,'http://local');if(u.pathname.startsWith('/api/manager-employee-users')){const handled=await handleManagerEmployeeUsers(req,res,u.pathname);if(handled)return}if(u.pathname.startsWith('/api/employee-')||u.pathname.startsWith('/api/manager-employee-')){const handled=await handleEmployeeApi(req,res,u.pathname);if(handled)return}if(u.pathname==='/api/consumers/location'||u.pathname==='/api/location-proposals'||u.pathname==='/api/consumers/location/approve'||u.pathname==='/api/consumers/location/reject'){const handled=await handleLocationApproval(req,res,u.pathname);if(handled)return}if(u.pathname==='/api/monthly'&&req.method==='GET'){await correctedMonthly(req,res,u);return}await proxy(req,res,req.url)});
server.listen(PORT,'0.0.0.0',()=>console.log(`ULGURJI_GATEWAY_V4_READY port=${PORT}`));
process.on('SIGTERM',()=>{child.kill('SIGTERM');server.close(()=>process.exit(0))});
process.on('SIGINT',()=>{child.kill('SIGINT');server.close(()=>process.exit(0))});
