import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {DatabaseSync} from 'node:sqlite';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const PORT=Number(process.env.PUBLIC_PORT||process.env.PORT||3000), INTERNAL=Number(process.env.INTERNAL_PORT||3001), DB=process.env.DB_PATH||'/app/data/data.sqlite';
const SECRET=process.env.JWT_SECRET||'CHANGE_THIS_SECRET_IN_PRODUCTION', GEO=Number(process.env.GEOFENCE_M||150), MAXACC=Number(process.env.GPS_MAX_ACCURACY_M||150), MAXAGE=Number(process.env.GPS_MAX_AGE_MS||180000);
const db=new DatabaseSync(DB); const q=s=>db.prepare(s), now=()=>new Date().toISOString(), sha=s=>crypto.createHash('sha256').update(String(s??'')).digest('hex'),b64=s=>Buffer.from(s).toString('base64url'),ub=s=>Buffer.from(s,'base64url').toString();
const norm=s=>String(s||'').trim().toLowerCase().replace(/[ʻ’‘`']/g,"'").replace(/\s+/g,' '), dateOk=x=>/^\d{4}-\d{2}-\d{2}$/.test(String(x||'')),monthOk=x=>/^\d{4}-\d{2}$/.test(String(x||'')),coord=(a,b)=>Number.isFinite(+a)&&Number.isFinite(+b)&&+a>=-90&&+a<=90&&+b>=-180&&+b<=180;
function verify(t){let a=t.split('.');if(a.length!==3)throw Error();let sig=b64(crypto.createHmac('sha256',SECRET).update(a[0]+'.'+a[1]).digest());if(sig!==a[2])throw Error();let p=JSON.parse(ub(a[1]));if(p.exp<Date.now()/1000)throw Error();return p}
function auth(req,res,admin=false){try{let h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw Error();let u=verify(h.slice(7));if(admin&&u.role!=='admin')throw Error('ADMIN');return u}catch(e){send(res,e.message==='ADMIN'?403:401,{error:e.message==='ADMIN'?'ADMIN_ONLY':'AUTH_INVALID'});return null}}
function send(res,c,d,type='application/json'){res.writeHead(c,{'Content-Type':type,'Cache-Control':'no-store','Access-Control-Allow-Origin':'*'});res.end(type.includes('json')?JSON.stringify(d):d)}
async function body(req){return await new Promise((ok,bad)=>{let x='';req.on('data',c=>{x+=c});req.on('end',()=>{try{ok(x?JSON.parse(x):{})}catch(e){bad(e)}})})}
function dist(a,b,c,d){let R=6371000,r=Math.PI/180,p1=a*r,p2=c*r,dp=(c-a)*r,dl=(d-b)*r,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(Math.min(1,x)))}
function audit(actor,action,payload){let prev=q('SELECT hash FROM audit ORDER BY id DESC LIMIT 1').get()?.hash||'GENESIS',ts=now(),body=JSON.stringify(payload??{}),hash=sha([prev,ts,actor||'',action,body].join('|'));q('INSERT INTO audit(ts_server,actor_id,action,payload,prev_hash,hash) VALUES(?,?,?,?,?,?)').run(ts,actor||null,action,body,prev,hash)}
function emp(id){return q("SELECT id,employee_name,region,district,position,phone FROM users WHERE id=? AND role='employee' AND active=1").get(id)}
function cons(id){return q('SELECT * FROM consumers WHERE id=? AND active=1').get(id)}
function territory(e,c){return !!e?.region&&!!e?.district&&!!c?.branch&&!!c?.district&&norm(e.region)===norm(c.branch)&&norm(e.district)===norm(c.district)}
function freshGps(id,lat,lon){let g=q('SELECT * FROM gps_points WHERE employee_id=? ORDER BY id DESC LIMIT 1').get(id);if(!g)return {ok:false,error:'GPS_TRACK_REQUIRED'};if(g.accuracy!=null&&+g.accuracy>MAXACC)return {ok:false,error:'GPS_ACCURACY_TOO_LOW',accuracy:g.accuracy};if(Date.now()-Date.parse(g.ts_server)>MAXAGE)return {ok:false,error:'GPS_TRACK_OLD'};let d=dist(+lat,+lon,+g.lat,+g.lon);if(d>200)return {ok:false,error:'GPS_MISMATCH',distance_m:d};return {ok:true}}
function proxy(req,res){let opts={hostname:'127.0.0.1',port:INTERNAL,path:req.url,method:req.method,headers:{...req.headers,host:'127.0.0.1:'+INTERNAL}};let p=http.request(opts,r=>{res.writeHead(r.statusCode||500,r.headers);r.pipe(res)});p.on('error',()=>send(res,502,{error:'UPSTREAM_OFFLINE'}));req.pipe(p)}
async function custom(req,res,url){
 try{
  if(req.method==='GET'&&url==='/api/me'){let u=auth(req,res);if(!u)return true;let e=emp(u.id);return send(res,200,{...u,...(e||{})}),true}
  if(req.method==='GET'&&url==='/api/employees'){let u=auth(req,res,true);if(!u)return true;return send(res,200,q("SELECT id,employee_name,login,active,region,district,position,phone FROM users WHERE role='employee' AND active=1 ORDER BY region,district,employee_name").all()),true}
  if(req.method==='GET'&&url==='/api/consumers'){let u=auth(req,res);if(!u)return true;let p=new URL(req.url,'http://x').searchParams,x=p.get('q')||'',page=Math.max(1,+(p.get('page')||1)),limit=Math.min(500,Math.max(1,+(p.get('limit')||100))),off=(page-1)*limit,w=x?' WHERE active=1 AND (name LIKE ? OR district LIKE ? OR branch LIKE ? OR mahalla LIKE ? OR phone LIKE ?)':' WHERE active=1',args=x?[`%${x}%`,`%${x}%`,`%${x}%`,`%${x}%`,`%${x}%`]:[],total=q(`SELECT COUNT(*) n FROM consumers${w}`).get(...args).n,items=q(`SELECT * FROM consumers${w} ORDER BY branch,district,name LIMIT ? OFFSET ?`).all(...args,limit,off);return send(res,200,{items,page,limit,total,has_more:off+items.length<total}),true}
  if(req.method==='POST'&&url==='/api/gps'){let u=auth(req,res);if(!u)return true;let b=await body(req);if(!coord(b.lat,b.lon)||!b.client_event_id)return send(res,400,{error:'GPS_INVALID'}),true;if(b.accuracy!=null&&+b.accuracy>MAXACC)return send(res,400,{error:'GPS_ACCURACY_TOO_LOW'}),true;let old=q('SELECT id,ts_server FROM gps_points WHERE client_event_id=?').get(String(b.client_event_id));if(old)return send(res,409,{error:'GPS_EVENT_ALREADY_EXISTS',gps_point_id:old.id,server_time:old.ts_server}),true;let ts=now();q('INSERT INTO gps_points(employee_id,ts_server,lat,lon,accuracy,speed,client_event_id) VALUES(?,?,?,?,?,?,?)').run(u.id,ts,+b.lat,+b.lon,b.accuracy??null,b.speed??null,String(b.client_event_id));audit(u.id,'GPS',b);return send(res,200,{ok:true,server_time:ts}),true}
  if(req.method==='POST'&&url==='/api/visit/start'){let u=auth(req,res);if(!u)return true;let b=await body(req),c=cons(b.consumer_id),e=emp(u.id);if(!c)return send(res,404,{error:'CONSUMER_NOT_FOUND'}),true;if(!coord(b.lat,b.lon)||!b.client_event_id)return send(res,400,{error:'LOCATION_REQUIRED'}),true;if(b.accuracy!=null&&+b.accuracy>MAXACC)return send(res,400,{error:'GPS_ACCURACY_TOO_LOW'}),true;if(!territory(e,c))return send(res,403,{error:'TERRITORY_MISMATCH'}),true;let dte=now().slice(0,10),a=q('SELECT id FROM assignments WHERE employee_id=? AND consumer_id=? AND work_date=?').get(u.id,b.consumer_id,dte);if(!a)return send(res,403,{error:'NOT_ASSIGNED_TODAY'}),true;if(!coord(c.lat,c.lon))return send(res,400,{error:'CONSUMER_LOCATION_MISSING'}),true;let g=freshGps(u.id,b.lat,b.lon);if(!g.ok)return send(res,403,g),true;let distance=dist(+b.lat,+b.lon,+c.lat,+c.lon);if(distance>GEO)return send(res,403,{error:'OUTSIDE_GEOFENCE',distance_m:distance,geofence_m:GEO}),true;let old=q('SELECT id,status,ended_server FROM visits WHERE client_event_id=?').get(String(b.client_event_id));if(old)return send(res,409,{error:'VISIT_EVENT_ALREADY_EXISTS',visit_id:old.id,status:old.status,ended_server:old.ended_server}),true;let open=q('SELECT id FROM visits WHERE employee_id=? AND consumer_id=? AND ended_server IS NULL').get(u.id,b.consumer_id);if(open)return send(res,409,{error:'VISIT_ALREADY_OPEN',visit_id:open.id}),true;let ts=now(),r=q('INSERT INTO visits(employee_id,consumer_id,started_server,start_lat,start_lon,start_accuracy,distance_m,status,client_event_id) VALUES(?,?,?,?,?,?,?,?,?)').run(u.id,b.consumer_id,ts,+b.lat,+b.lon,b.accuracy??null,distance,'VALID',String(b.client_event_id));audit(u.id,'VISIT_START',{...b,distance_m:distance,status:'VALID'});return send(res,200,{ok:true,visit_id:Number(r.lastInsertRowid),server_time:ts,distance_m:distance,status:'VALID'}),true}
  if(req.method==='POST'&&url==='/api/visit/end'){let u=auth(req,res);if(!u)return true;let b=await body(req),v=q('SELECT * FROM visits WHERE id=? AND employee_id=?').get(b.visit_id,u.id);if(!v)return send(res,404,{error:'VISIT_NOT_FOUND'}),true;if(v.ended_server)return send(res,409,{error:'VISIT_ALREADY_CLOSED'}),true;if(!coord(b.lat,b.lon))return send(res,400,{error:'LOCATION_REQUIRED'}),true;let g=freshGps(u.id,b.lat,b.lon);if(!g.ok)return send(res,403,g),true;let d=dist(+b.lat,+b.lon,+v.start_lat,+v.start_lon);if(d>1000)return send(res,403,{error:'END_LOCATION_MISMATCH',distance_m:d}),true;let ts=now();q('UPDATE visits SET ended_server=?,end_lat=?,end_lon=?,end_accuracy=? WHERE id=?').run(ts,+b.lat,+b.lon,b.accuracy??null,b.visit_id);audit(u.id,'VISIT_END',b);return send(res,200,{ok:true,server_time:ts}),true}
  if(req.method==='GET'&&url==='/api/employee-profile'){let u=auth(req,res);if(!u)return true;return send(res,200,emp(u.id)||u)}
  if(req.method==='GET'&&url==='/api/assignments'){let u=auth(req,res,true);if(!u)return true;let p=new URL(req.url,'http://x').searchParams,d=dateOk(p.get('date'))?p.get('date'):now().slice(0,10),eid=p.get('employee_id');let sql=`SELECT a.*,u.employee_name,u.region employee_region,u.district employee_district,c.name consumer_name,c.branch consumer_region,c.district consumer_district,c.mahalla,c.lat,c.lon FROM assignments a JOIN users u ON u.id=a.employee_id JOIN consumers c ON c.id=a.consumer_id WHERE a.work_date=?`;let args=[d];if(eid){sql+=' AND a.employee_id=?';args.push(+eid)}return send(res,200,{date:d,items:q(sql+' ORDER BY u.region,u.district,u.employee_name,c.name').all(...args)})}
  if(req.method==='POST'&&url==='/api/assign'){let u=auth(req,res,true);if(!u)return true;let b=await body(req);if(!dateOk(b.work_date))return send(res,400,{error:'ASSIGNMENT_INVALID'}),true;let e=emp(b.employee_id),c=cons(b.consumer_id);if(!e||!c)return send(res,404,{error:'EMPLOYEE_OR_CONSUMER_NOT_FOUND'}),true;if(!territory(e,c))return send(res,403,{error:'TERRITORY_MISMATCH',employee_region:e.region,employee_district:e.district,consumer_region:c.branch,consumer_district:c.district}),true;q('INSERT OR IGNORE INTO assignments(employee_id,consumer_id,work_date) VALUES(?,?,?)').run(b.employee_id,b.consumer_id,b.work_date);audit(u.id,'ASSIGN',b);return send(res,200,{ok:true}),true}
  if(req.method==='POST'&&url==='/api/consumers'){let u=auth(req,res,true);if(!u)return true;let b=await body(req);if(!b.name||!b.branch||!b.district)return send(res,400,{error:'CONSUMER_REQUIRED'}),true;let r=q('INSERT INTO consumers(name,branch,district,mahalla,street,category,activity,phone,lat,lon,location_accuracy,location_set_server,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,1)').run(b.name,b.branch,b.district,b.mahalla||null,b.street||null,b.category||null,b.activity||null,b.phone||null,b.lat??null,b.lon??null,b.accuracy??null,b.lat!=null?now():null);audit(u.id,'CONSUMER_CREATE',b);return send(res,201,{ok:true,consumer_id:Number(r.lastInsertRowid)}),true}
  if(req.method==='GET'&&url==='/api/route'){let u=auth(req,res);if(!u)return true;let p=new URL(req.url,'http://x').searchParams,d=dateOk(p.get('date'))?p.get('date'):now().slice(0,10),eid=u.role==='admin'?+(p.get('employee_id')||0):u.id;if(!eid)return send(res,400,{error:'EMPLOYEE_REQUIRED'}),true;return send(res,200,{date:d,employee_id:eid,points:q('SELECT id,ts_server,lat,lon,accuracy,speed FROM gps_points WHERE employee_id=? AND ts_server LIKE ? ORDER BY id').all(eid,`${d}%`)}),true}
  if(req.method==='GET'&&url==='/api/monthly'){let u=auth(req,res,true);if(!u)return true;let p=new URL(req.url,'http://x').searchParams,m=monthOk(p.get('month'))?p.get('month'):now().slice(0,7);return send(res,200,{month:m,result:q(`SELECT u.id employee_id,u.employee_name,u.region,u.district,COUNT(DISTINCT a.consumer_id||':'||a.work_date) planned_days,COUNT(DISTINCT v.id) visits,COUNT(DISTINCT CASE WHEN v.status='VALID' THEN v.id END) valid_visits FROM users u LEFT JOIN assignments a ON a.employee_id=u.id AND a.work_date LIKE ? LEFT JOIN visits v ON v.employee_id=u.id AND v.started_server LIKE ? WHERE u.role='employee' AND u.active=1 GROUP BY u.id ORDER BY u.region,u.district,u.employee_name`).all(`${m}%`,`${m}%`)}),true}
  if(req.method==='GET'&&url==='/api/consumer-monthly'){let u=auth(req,res,true);if(!u)return true;let p=new URL(req.url,'http://x').searchParams,m=monthOk(p.get('month'))?p.get('month'):now().slice(0,7),x=p.get('q')||'',w=x?' AND (c.name LIKE ? OR c.district LIKE ? OR c.branch LIKE ?)':'';let args=x?[`${m}%`,`%${x}%`,`%${x}%`,`%${x}%`]:[`${m}%`];return send(res,200,{month:m,result:q(`SELECT c.id,c.name,c.branch,c.district,c.mahalla,COUNT(DISTINCT v.id) visits,COUNT(DISTINCT v.employee_id) employees,MAX(v.started_server) last_visit FROM consumers c LEFT JOIN visits v ON v.consumer_id=c.id AND v.started_server LIKE ? WHERE c.active=1${w} GROUP BY c.id ORDER BY visits DESC,c.name LIMIT 500`).all(...args)}),true}
  if(req.method==='GET'&&url==='/api/audit-check'){let u=auth(req,res,true);if(!u)return true;let rows=q('SELECT * FROM audit ORDER BY id DESC LIMIT 500').all(),rev=[...rows].reverse(),prev='GENESIS',valid=true,bad=null;for(let r of rev){let ex=sha([prev,r.ts_server,r.actor_id||'',r.action,r.payload].join('|'));if(ex!==r.hash||r.prev_hash!==prev){valid=false;bad={id:r.id,expected:ex,actual:r.hash,prev_expected:prev,prev_actual:r.prev_hash};break}prev=r.hash}return send(res,200,{chain_valid:valid,count:rows.length,bad}),true}
  return false;
 }catch(e){return send(res,500,{error:e.message||'SERVER_ERROR'}),true}
}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Authorization,Content-Type'});return res.end()}let url=new URL(req.url,'http://x').pathname;if(url.startsWith('/api/')){let done=await custom(req,res,url);if(done)return;return proxy(req,res)}if(url==='/'||url.startsWith('/app-fixed.js')||url.startsWith('/index.html')){let file=url.startsWith('/app-fixed.js')?'app-fixed.js':'index.html',p=path.join(__dirname,'public',file);if(fs.existsSync(p)){res.writeHead(200,{'Content-Type':file.endsWith('.js')?'text/javascript; charset=utf-8':'text/html; charset=utf-8','Cache-Control':'no-cache'});return fs.createReadStream(p).pipe(res)}}return proxy(req,res)});server.listen(PORT,()=>console.log('ULGURJI GATEWAY V4:'+PORT));