import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';

// Suppress only Node's SQLite ExperimentalWarning before loading node:sqlite.
// This is intentionally installed before the dynamic import because a static
// import is evaluated before this module's code can run.
const defaultWarningListeners = process.listeners('warning');
for (const listener of defaultWarningListeners) process.removeListener('warning', listener);
process.on('warning', warning => {
  const message = String(warning?.message || '');
  if (warning?.name === 'ExperimentalWarning' && message.includes('SQLite is an experimental feature')) return;
  process.stderr.write(`${warning?.stack || warning}\n`);
});

const {DatabaseSync} = await import('node:sqlite');
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const PORT=Number(process.env.PORT||3000),DB_PATH=process.env.DB_PATH||path.join(__dirname,'data.sqlite');
const SECRET=process.env.JWT_SECRET||'ULGURJI_CHANGE_SECRET',GEOFENCE_M=Number(process.env.GEOFENCE_M||150),GPS_MAX_ACCURACY_M=Number(process.env.GPS_MAX_ACCURACY_M||150),GPS_MAX_AGE_MS=Number(process.env.GPS_MAX_AGE_MS||180000),GPS_MAX_JUMP_M=Number(process.env.GPS_MAX_JUMP_M||200);
const db=new DatabaseSync(DB_PATH);db.exec(`PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,login TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL,employee_name TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);CREATE TABLE IF NOT EXISTS consumers(id INTEGER PRIMARY KEY,name TEXT,branch TEXT,district TEXT,mahalla TEXT,street TEXT,category TEXT,activity TEXT,phone TEXT,lat REAL,lon REAL,location_accuracy REAL,location_set_server TEXT,active INTEGER DEFAULT 1);CREATE TABLE IF NOT EXISTS assignments(id INTEGER PRIMARY KEY AUTOINCREMENT,employee_id INTEGER NOT NULL,consumer_id INTEGER NOT NULL,work_date TEXT NOT NULL,UNIQUE(employee_id,consumer_id,work_date));CREATE TABLE IF NOT EXISTS visits(id INTEGER PRIMARY KEY AUTOINCREMENT,employee_id INTEGER NOT NULL,consumer_id INTEGER NOT NULL,started_server TEXT NOT NULL,ended_server TEXT,start_lat REAL,start_lon REAL,start_accuracy REAL,end_lat REAL,end_lon REAL,end_accuracy REAL,distance_m REAL,status TEXT NOT NULL,client_event_id TEXT UNIQUE NOT NULL);CREATE TABLE IF NOT EXISTS gps_points(id INTEGER PRIMARY KEY AUTOINCREMENT,employee_id INTEGER NOT NULL,ts_server TEXT NOT NULL,lat REAL NOT NULL,lon REAL NOT NULL,accuracy REAL,speed REAL,client_event_id TEXT UNIQUE NOT NULL);CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,ts_server TEXT NOT NULL,actor_id INTEGER,action TEXT NOT NULL,payload TEXT NOT NULL,prev_hash TEXT,hash TEXT NOT NULL);CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT DEFAULT '',work_date TEXT NOT NULL,employee_id INTEGER NOT NULL,created_by INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'ASSIGNED',result_text TEXT DEFAULT '',completed_at TEXT,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS task_files(id INTEGER PRIMARY KEY AUTOINCREMENT,task_id INTEGER NOT NULL,uploaded_by INTEGER NOT NULL,filename TEXT NOT NULL,mime TEXT DEFAULT 'application/octet-stream',data BLOB NOT NULL,uploaded_at TEXT NOT NULL);`);
for(const s of ['ALTER TABLE users ADD COLUMN region TEXT','ALTER TABLE users ADD COLUMN district TEXT','ALTER TABLE users ADD COLUMN position TEXT','ALTER TABLE users ADD COLUMN phone TEXT','ALTER TABLE consumers ADD COLUMN region TEXT','ALTER TABLE visits ADD COLUMN outcome TEXT','ALTER TABLE visits ADD COLUMN notes TEXT']){try{db.exec(s)}catch(e){if(!String(e.message).toLowerCase().includes('duplicate column'))throw e}}
const q=s=>db.prepare(s),now=()=>new Date().toISOString(),sha=s=>crypto.createHash('sha256').update(String(s??'')).digest('hex'),b64=s=>Buffer.from(s).toString('base64url'),ub=s=>Buffer.from(s,'base64url').toString();
const dateOk=x=>/^\d{4}-\d{2}-\d{2}$/.test(String(x||'')),monthOk=x=>/^\d{4}-\d{2}$/.test(String(x||'')),coord=(a,b)=>Number.isFinite(+a)&&Number.isFinite(+b)&&+a>=-90&&+a<=90&&+b>=-180&&+b<=180,norm=s=>String(s??'').trim().toLowerCase().replace(/[ʻ’‘`']/g,"'").replace(/[–—-]/g,' ').replace(/\s+/g,' '),regionNorm=s=>{const x=norm(s),m={'ққр':'қорақалпоғистон республикаси','анд':'андижон вилояти','бух':'бухоро вилояти','жиз':'жиззах вилояти','қаш':'қашқадарё вилояти','нав':'навоий вилояти','нам':'наманган вилояти','сам':'самарқанд вилояти','сур':'сурхондарё вилояти','сир':'сирдарё вилояти','тош':'тошкент вилояти','фар':'фарғона вилояти','хор':'хоразм вилояти','пой':'тошкент шаҳри'};return m[x]||x};
const distanceM=(a,b,c,d)=>{const R=6371000,r=Math.PI/180,p1=+a*r,p2=+c*r,dp=(+c-+a)*r,dl=(+d-+b)*r,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(Math.min(1,x)))};
const employee=id=>q("SELECT id,login,employee_name,role,active,region,district,position,phone FROM users WHERE id=? AND role='employee' AND active=1").get(id),consumer=id=>q('SELECT * FROM consumers WHERE id=? AND active=1').get(id),assigned=(e,c,d=now().slice(0,10))=>!!q('SELECT 1 FROM assignments WHERE employee_id=? AND consumer_id=? AND work_date=?').get(e,c,d);