import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {DatabaseSync} from 'node:sqlite';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const PORT=Number(process.env.PORT||3000),DB_PATH=process.env.DB_PATH||path.join(__dirname,'data.sqlite');
const SECRET=process.env.JWT_SECRET||'ULGURJI_CHANGE_SECRET',GEOFENCE_M=Number(process.env.GEOFENCE_M||150),GPS_MAX_ACCURACY_M=Number(process.env.GPS_MAX_ACCURACY_M||150),GPS_MAX_AGE_MS=Number(process.env.GPS_MAX_AGE_MS||180000),GPS_MAX_JUMP_M=Number(process.env.GPS_MAX_JUMP_M||200);
const db=new DatabaseSync(DB_PATH);db.exec(`PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,login TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL,employee_name TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);CREATE TABLE IF NOT EXISTS consumers(id INTEGER PRIMARY KEY,name TEXT,branch TEXT,district TEXT,mahalla TEXT,street TEXT,category TEXT,activity TEXT,phone TEXT,lat REAL,lon REAL,location_accuracy REAL,location_set_server TEXT,active INTEGER DEFAULT 1);CREATE TABLE IF NOT EXISTS assignments(id INTEGER PRIMARY KEY AUTOINCREMENT,employee_id INTEGER NOT NULL,consumer_id INTEGER NOT NULL,work_date TEXT NOT NULL,UNIQUE(employee_id,consumer_id,work_date));CREATE TABLE IF NOT EXISTS visits(id INTEGER PRIMARY KEY AUTOINCREMENT,employee_id INTEGER NOT NULL,consumer_id INTEGER NOT NULL,started_server TEXT NOT NULL,ended_server TEXT,start_lat REAL,start_lon REAL,start_accuracy REAL,end_lat REAL,end_lon REAL,end_accuracy REAL,distance_m REAL,status TEXT NOT NULL,client_event_id TEXT UNIQUE NOT NULL);CREATE TABLE IF NOT EXISTS gps_points(id INTEGER PRIMARY KEY AUTOINCREMENT,employee_id INTEGER NOT NULL,ts_server TEXT NOT NULL,lat REAL NOT NULL,lon REAL NOT NULL,accuracy REAL,speed REAL,client_event_id TEXT UNIQUE NOT NULL);CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,ts_server TEXT NOT NULL,actor_id INTEGER,action TEXT NOT NULL,payload TEXT NOT NULL,prev_hash TEXT,hash TEXT NOT NULL);CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT DEFAULT '',work_date TEXT NOT NULL,employee_id INTEGER NOT NULL,created_by INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'ASSIGNED',result_text TEXT DEFAULT '',completed_at TEXT,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS task_files(id INTEGER PRIMARY KEY AUTOINCREMENT,task_id INTEGER NOT NULL,uploaded_by INTEGER NOT NULL,filename TEXT NOT NULL,mime TEXT DEFAULT 'application/octet-stream',data BLOB NOT NULL,uploaded_at TEXT NOT NULL);`);
for(const s of ['ALTER TABLE users ADD COLUMN region TEXT','ALTER TABLE users ADD COLUMN district TEXT','ALTER TABLE users ADD COLUMN position TEXT','ALTER TABLE users ADD COLUMN phone TEXT','ALTER TABLE consumers ADD COLUMN region TEXT','ALTER TABLE visits ADD COLUMN outcome TEXT','ALTER TABLE visits ADD COLUMN notes TEXT']){try{db.exec(s)}catch(e){if(!String(e.message).toLowerCase().includes('duplicate column'))throw e}}
const q=s=>db.prepare(s),now=()=>new Date().toISOString(),sha=s=>crypto.createHash('sha256').update(String(s??'')).digest('hex'),b64=s=>Buffer.from(s).toString('base64url'),ub=s=>Buffer.from(s,'base64url').toString();
const dateOk=x=>/^\d{4}-\d{2}-\d{2}$/.test(String(x||'')),monthOk=x=>/^\d{4}-\d{2}$/.test(String(x||'')),coord=(a,b)=>Number.isFinite(+a)&&Number.isFinite(+b)&&+a>=-90&&+a<=90&&+b>=-180&&+b<=180,norm=s=>String(s??'').trim().toLowerCase().replace(/[ʻ’‘`']/g,"'").replace(/[–—-]/g,' ').replace(/\s+/g,' '),regionNorm=s=>{const x=norm(s),m={'ққр':'қорақалпоғистон республикаси','анд':'андижон вилояти','бух':'бухоро вилояти','жиз':'жиззах вилояти','қаш':'қашқадарё вилояти','нав':'навоий вилояти','нам':'наманган вилояти','сам':'самарқанд вилояти','сур':'сурхондарё вилояти','сир':'сирдарё вилояти','тош':'тошкент вилояти','фар':'фарғона вилояти','хор':'хоразм вилояти','пой':'тошкент шаҳри'};return m[x]||x};
const distanceM=(a,b,c,d)=>{const R=6371000,r=Math.PI/180,p1=+a*r,p2=+c*r,dp=(+c-+a)*r,dl=(+d-+b)*r,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(Math.min(1,x)))};
const employee=id=>q("SELECT id,login,employee_name,role,active,region,district,position,phone FROM users WHERE id=? AND role='employee' AND active=1").get(id),consumer=id=>q('SELECT * FROM consumers WHERE id=? AND active=1').get(id),assigned=(e,c,d=now().slice(0,10))=>!!q('SELECT 1 FROM assignments WHERE employee_id=? AND consumer_id=? AND work_date=?').get(e,c,d);
function territory(e,c){const er=e?.region,cr=c?.region||c?.branch,ed=e?.district,cd=c?.district;if(!er||!cr||regionNorm(er)!==regionNorm(cr))return false;return !ed||!cd||norm(ed)===norm(cd)}
function jwt(p){const h=b64(JSON.stringify({alg:'HS256',typ:'JWT'})),b=b64(JSON.stringify({...p,exp:Math.floor(Date.now()/1000)+43200})),s=b64(crypto.createHmac('sha256',SECRET).update(h+'.'+b).digest());return h+'.'+b+'.'+s}
function verify(t){const a=String(t||'').split('.');if(a.length!==3)throw Error('AUTH_INVALID');const s=b64(crypto.createHmac('sha256',SECRET).update(a[0]+'.'+a[1]).digest());if(s!==a[2])throw Error('AUTH_INVALID');const p=JSON.parse(ub(a[1]));if(!p.exp||p.exp<Date.now()/1000)throw Error('AUTH_INVALID');return p}
function auth(req,res,admin=false){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw Error('AUTH_INVALID');const u=verify(h.slice(7));if(admin&&u.role!=='admin')throw Error('ADMIN_ONLY');return u}catch(e){send(res,e.message==='ADMIN_ONLY'?403:401,{error:e.message==='ADMIN_ONLY'?'ADMIN_ONLY':'AUTH_INVALID'});return null}}
function send(res,c,d,t='application/json',h={}){res.writeHead(c,{'Content-Type':t,'Cache-Control':'no-store, no-cache, must-revalidate','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Allow-Methods':'GET, POST, PUT, PATCH, DELETE, OPTIONS',...h});res.end(t.includes('json')?JSON.stringify(d):d)}
async function body(req,max=10e6){return await new Promise((ok,no)=>{let a=[],n=0;req.on('data',c=>{n+=c.length;if(n>max){no(Error('BODY_TOO_LARGE'));req.destroy();return}a.push(c)});req.on('end',()=>ok(Buffer.concat(a)));req.on('error',no)})}
async function json(req){return JSON.parse((await body(req)).toString('utf8')||'{}')}
function audit(actor,action,payload){const prev=q('SELECT hash FROM audit ORDER BY id DESC LIMIT 1').get()?.hash||'GENESIS',ts=now(),p=JSON.stringify(payload??{}),h=sha([prev,ts,actor||'',action,p].join('|'));q('INSERT INTO audit(ts_server,actor_id,action,payload,prev_hash,hash) VALUES(?,?,?,?,?,?)').run(ts,actor||null,action,p,prev,h)}
q("INSERT OR IGNORE INTO users(id,login,password_hash,role,employee_name) VALUES(1,'admin',?,'admin','Раҳбар')").run(sha(process.env.ADMIN_PASSWORD||'Ulgurji2026Admin'));
try{await import('./import-employees.js')}catch(e){console.error('EMPLOYEE_IMPORT_ERROR',e)}
function tasksFor(u,d){const day=dateOk(d)?d:now().slice(0,10);return q(`SELECT t.*,u.employee_name,u.region,u.district,(SELECT COUNT(*) FROM task_files f WHERE f.task_id=t.id) files_count FROM tasks t LEFT JOIN users u ON u.id=t.employee_id WHERE ${u.role==='admin'?'t.work_date=?':'t.employee_id=? AND t.work_date=?'} ORDER BY CASE t.status WHEN 'NOT_COMPLETED' THEN 0 WHEN 'IN_PROGRESS' THEN 1 WHEN 'ASSIGNED' THEN 2 ELSE 3 END,t.id DESC`).all(...(u.role==='admin'?[day]:[u.id,day]))}
function fileName(s){return path.basename(String(s||'photo')).replace(/[^\p{L}\p{N}._ -]/gu,'_').slice(0,120)||'photo'}
function fileRows(id){return q('SELECT id,task_id,filename,mime,LENGTH(data) size,uploaded_at FROM task_files WHERE task_id=? ORDER BY id').all(id)}
async function api(req,res,url){try{
if(req.method==='GET'&&url==='/api/health')return send(res,200,{ok:true,time:now(),db:'sqlite',geofence_m:GEOFENCE_M});
if(req.method==='POST'&&url==='/api/login'){const b=await json(req),u=q('SELECT * FROM users WHERE login=? AND active=1').get(String(b.login||'').trim());if(!u||sha(b.password)!==u.password_hash)return send(res,401,{error:'LOGIN_FAILED'});const p={id:u.id,role:u.role,name:u.employee_name,region:u.region||'',district:u.district||'',position:u.position||'',phone:u.phone||''};audit(u.id,'LOGIN',{login:u.login});return send(res,200,{token:jwt(p),user:p})}
if(req.method==='GET'&&url==='/api/me'){const u=auth(req,res);if(!u)return;const r=q('SELECT * FROM users WHERE id=? AND active=1').get(u.id);if(!r)return send(res,401,{error:'AUTH_INVALID'});return send(res,200,{id:r.id,login:r.login,role:r.role,name:r.employee_name,region:r.region||'',district:r.district||'',position:r.position||'',phone:r.phone||''})}
if(req.method==='GET'&&url==='/api/metrics'){const u=auth(req,res,true);if(!u)return;const consumers=q('SELECT COUNT(*) n FROM consumers WHERE active=1').get().n,located=q('SELECT COUNT(*) n FROM consumers WHERE active=1 AND lat IS NOT NULL AND lon IS NOT NULL').get().n,employees=q("SELECT COUNT(*) n FROM users WHERE role='employee' AND active=1").get().n,assignments=q('SELECT COUNT(*) n FROM assignments').get().n,visits=q('SELECT COUNT(*) n FROM visits').get().n,gps_points=q('SELECT COUNT(*) n FROM gps_points').get().n,auditCount=q('SELECT COUNT(*) n FROM audit').get().n;return send(res,200,{consumers,located,unlocated:consumers-located,employees,assignments,visits,gps_points,audit:auditCount,integrity:q('PRAGMA integrity_check').get().integrity_check,geofence_m:GEOFENCE_M})}
if(req.method==='GET'&&url==='/api/employees'){const u=auth(req,res,true);if(!u)return;return send(res,200,q("SELECT id,employee_name,login,active,region,district,position,phone FROM users WHERE role='employee' AND active=1 ORDER BY region,district,employee_name").all())}
if(req.method==='GET'&&url==='/api/consumers'){const u=auth(req,res);if(!u)return;const p=new URL(req.url,'http://x').searchParams,term=String(p.get('q')||'').trim(),page=Math.max(1,+(p.get('page')||1)),limit=Math.min(500,Math.max(1,+(p.get('limit')||100))),off=(page-1)*limit;let w='c.active=1',args=[];if(u.role==='employee'){w+=' AND a.employee_id=? AND a.work_date=?';args.push(u.id,now().slice(0,10))}if(term){w+=' AND (c.name LIKE ? OR c.district LIKE ? OR c.branch LIKE ? OR c.region LIKE ? OR c.mahalla LIKE ? OR c.street LIKE ? OR c.phone LIKE ?)';args.push(...Array(7).fill('%'+term+'%'))}const from=u.role==='employee'?'consumers c JOIN assignments a ON a.consumer_id=c.id':'consumers c',total=q(`SELECT COUNT(*) n FROM ${from} WHERE ${w}`).get(...args).n,items=q(`SELECT c.* FROM ${from} WHERE ${w} ORDER BY c.branch,c.district,c.name LIMIT ? OFFSET ?`).all(...args,limit,off);return send(res,200,{items,page,limit,total,has_more:off+items.length<total})}
if(req.method==='GET'&&url.startsWith('/api/consumers/')){const u=auth(req,res);if(!u)return;const c=consumer(Number(url.split('/').pop()));if(!c)return send(res,404,{error:'CONSUMER_NOT_FOUND'});if(u.role==='employee'&&!assigned(u.id,c.id))return send(res,403,{error:'NOT_ASSIGNED_TODAY'});return send(res,200,c)}
if(req.method==='GET'&&url==='/api/today'){const u=auth(req,res);if(!u)return;const p=new URL(req.url,'http://x').searchParams,d=dateOk(p.get('date'))?p.get('date'):now().slice(0,10),eid=u.role==='employee'?u.id:+(p.get('employee_id')||0);if(!eid)return send(res,403,{error:'ADMIN_ONLY'});const rows=q(`SELECT a.id assignment_id,c.*,v.id visit_id,v.started_server,v.ended_server,v.status visit_status,v.distance_m,v.outcome,v.notes FROM assignments a JOIN consumers c ON c.id=a.consumer_id LEFT JOIN visits v ON v.employee_id=a.employee_id AND v.consumer_id=a.consumer_id AND substr(v.started_server,1,10)=a.work_date WHERE a.employee_id=? AND a.work_date=? ORDER BY c.name`).all(eid,d);return send(res,200,{date:d,items:rows})}
if(req.method==='POST'&&url==='/api/gps'){const u=auth(req,res);if(!u||u.role!=='employee')return send(res,403,{error:'EMPLOYEE_ONLY'});const b=await json(req);if(!coord(b.lat,b.lon)||!b.client_event_id)return send(res,400,{error:'GPS_INVALID'});if(q('SELECT id FROM gps_points WHERE client_event_id=?').get(String(b.client_event_id)))return send(res,409,{error:'GPS_EVENT_ALREADY_EXISTS'});q('INSERT INTO gps_points(employee_id,ts_server,lat,lon,accuracy,speed,client_event_id) VALUES(?,?,?,?,?,?,?)').run(u.id,now(),+b.lat,+b.lon,b.accuracy==null?null:+b.accuracy,b.speed==null?null:+b.speed,String(b.client_event_id));return send(res,200,{ok:true,server_time:now()})}
if(req.method==='POST'&&url==='/api/consumers/location'){const u=auth(req,res);if(!u)return;const b=await json(req),c=consumer(+b.consumer_id);if(!c)return send(res,404,{error:'CONSUMER_NOT_FOUND'});if(u.role==='employee'){if(!assigned(u.id,c.id)||!territory(employee(u.id),c))return send(res,403,{error:'TERRITORY_MISMATCH'});if(!coord(b.lat,b.lon))return send(res,400,{error:'GPS_INVALID'})}else if(!coord(b.lat,b.lon))return send(res,400,{error:'GPS_INVALID'});q('UPDATE consumers SET lat=?,lon=?,location_accuracy=?,location_set_server=?,region=COALESCE(region,?) WHERE id=?').run(+b.lat,+b.lon,b.accuracy==null?null:+b.accuracy,now(),u.region||c.region||c.branch,c.id);audit(u.id,'CONSUMER_LOCATION',{consumer_id:c.id});return send(res,200,{ok:true,consumer_id:c.id})}
if(req.method==='POST'&&url==='/api/assign'){const u=auth(req,res,true);if(!u)return;const b=await json(req),e=employee(+b.employee_id),c=consumer(+b.consumer_id),d=dateOk(b.work_date)?b.work_date:now().slice(0,10);if(!e||!c)return send(res,404,{error:'NOT_FOUND'});if(!territory(e,c))return send(res,403,{error:'TERRITORY_MISMATCH'});q('INSERT OR IGNORE INTO assignments(employee_id,consumer_id,work_date) VALUES(?,?,?)').run(e.id,c.id,d);audit(u.id,'ASSIGN',{employee_id:e.id,consumer_id:c.id,work_date:d});return send(res,200,{ok:true})}
if(req.method==='POST'&&url==='/api/visit/start'){const u=auth(req,res);if(!u||u.role!=='employee')return send(res,403,{error:'EMPLOYEE_ONLY'});const b=await json(req),c=consumer(+b.consumer_id),d=now().slice(0,10);if(!c)return send(res,404,{error:'CONSUMER_NOT_FOUND'});if(!assigned(u.id,c.id,d))return send(res,403,{error:'NOT_ASSIGNED_TODAY'});if(!territory(u,c))return send(res,403,{error:'TERRITORY_MISMATCH'});if(!coord(b.lat,b.lon)||!b.client_event_id)return send(res,400,{error:'GPS_INVALID'});const g=q('SELECT * FROM gps_points WHERE employee_id=? ORDER BY id DESC LIMIT 1').get(u.id);if(!g||Date.now()-Date.parse(g.ts_server)>GPS_MAX_AGE_MS)return send(res,400,{error:'GPS_TRACK_OLD'});if(g.accuracy!=null&&+g.accuracy>GPS_MAX_ACCURACY_M)return send(res,400,{error:'GPS_ACCURACY_TOO_LOW'});if(c.lat==null||c.lon==null)return send(res,400,{error:'CONSUMER_LOCATION_MISSING'});const dist=distanceM(b.lat,b.lon,c.lat,c.lon);if(dist>GEOFENCE_M)return send(res,403,{error:'OUTSIDE_GEOFENCE',distance_m:dist,geofence_m:GEOFENCE_M});if(q('SELECT id FROM visits WHERE employee_id=? AND consumer_id=? AND ended_server IS NULL').get(u.id,c.id))return send(res,409,{error:'VISIT_EVENT_ALREADY_EXISTS'});const r=q('INSERT INTO visits(employee_id,consumer_id,started_server,start_lat,start_lon,start_accuracy,distance_m,status,client_event_id) VALUES(?,?,?,?,?,?,?,?,?)').run(u.id,c.id,now(),+b.lat,+b.lon,b.accuracy==null?null:+b.accuracy,dist,'VALID',String(b.client_event_id));audit(u.id,'VISIT_START',{consumer_id:c.id,visit_id:r.lastInsertRowid,status:'VALID',distance_m:dist});return send(res,200,{ok:true,visit_id:Number(r.lastInsertRowid),status:'VALID',distance_m:dist})}
if(req.method==='POST'&&url==='/api/visit/end'){const u=auth(req,res);if(!u||u.role!=='employee')return send(res,403,{error:'EMPLOYEE_ONLY'});const b=await json(req),v=q('SELECT * FROM visits WHERE id=? AND employee_id=?').get(+b.visit_id,u.id);if(!v)return send(res,404,{error:'VISIT_NOT_FOUND'});if(v.ended_server)return send(res,409,{error:'VISIT_EVENT_ALREADY_EXISTS'});if(!coord(b.lat,b.lon))return send(res,400,{error:'GPS_INVALID'});const ts=now();q('UPDATE visits SET ended_server=?,end_lat=?,end_lon=?,end_accuracy=?,outcome=?,notes=? WHERE id=?').run(ts,+b.lat,+b.lon,b.accuracy==null?null:+b.accuracy,String(b.outcome||''),String(b.notes||''),v.id);audit(u.id,'VISIT_END',{visit_id:v.id});return send(res,200,{ok:true,visit_id:v.id})}
if(req.method==='GET'&&url==='/api/live'){const u=auth(req,res,true);if(!u)return;return send(res,200,{rows:q(`SELECT g.employee_id,u.employee_name,u.region,u.district,g.ts_server,g.lat,g.lon,g.accuracy FROM gps_points g JOIN users u ON u.id=g.employee_id WHERE g.id IN (SELECT MAX(id) FROM gps_points GROUP BY employee_id) ORDER BY u.region,u.district,u.employee_name`).all()})}
if(req.method==='GET'&&url==='/api/report'){const u=auth(req,res,true);if(!u)return;const d=new URL(req.url,'http://x').searchParams.get('date'),day=dateOk(d)?d:now().slice(0,10),r=q(`SELECT u.id employee_id,u.employee_name employee,u.region,u.district,COUNT(DISTINCT a.id) planned,COUNT(DISTINCT CASE WHEN v.id IS NOT NULL THEN v.id END) visited,COUNT(DISTINCT CASE WHEN a.id IS NOT NULL AND v.id IS NULL THEN a.id END) not_visited,COUNT(DISTINCT CASE WHEN v.id IS NOT NULL AND v.status!='VALID' THEN v.id END) suspicious FROM users u LEFT JOIN assignments a ON a.employee_id=u.id AND a.work_date=? LEFT JOIN visits v ON v.employee_id=a.employee_id AND v.consumer_id=a.consumer_id AND substr(v.started_server,1,10)=? WHERE u.role='employee' AND u.active=1 GROUP BY u.id ORDER BY u.region,u.district,u.employee_name`).all(day,day).map(x=>({...x,completion:x.planned?Math.round(x.visited/x.planned*100):0}));return send(res,200,{date:day,result:r})}
if(req.method==='GET'&&url==='/api/monthly'){const u=auth(req,res,true);if(!u)return;const m=new URL(req.url,'http://x').searchParams.get('month'),mm=monthOk(m)?m:now().slice(0,7),r=q(`SELECT u.id employee_id,u.employee_name,u.region,u.district,COUNT(DISTINCT a.id) planned,COUNT(DISTINCT v.id) visited,COUNT(DISTINCT CASE WHEN v.status='VALID' THEN v.id END) valid,COUNT(DISTINCT CASE WHEN v.status!='VALID' THEN v.id END) suspicious FROM users u LEFT JOIN assignments a ON a.employee_id=u.id AND substr(a.work_date,1,7)=? LEFT JOIN visits v ON v.employee_id=u.id AND substr(v.started_server,1,7)=? WHERE u.role='employee' AND u.active=1 GROUP BY u.id ORDER BY u.region,u.district,u.employee_name`).all(mm,mm).map(x=>({...x,completion:x.planned?Math.round(x.visited/x.planned*100):0}));return send(res,200,{month:mm,result:r})}
if(req.method==='GET'&&url==='/api/consumer-monthly'){const u=auth(req,res,true);if(!u)return;const p=new URL(req.url,'http://x').searchParams,m=p.get('month'),mm=monthOk(m)?m:now().slice(0,7),page=Math.max(1,+(p.get('page')||1)),limit=Math.min(500,Math.max(50,+(p.get('limit')||200))),off=(page-1)*limit;const r=q(`SELECT c.id consumer_id,c.name,c.region,c.branch,c.district,COUNT(v.id) visits,COUNT(DISTINCT v.employee_id) employees,MAX(v.started_server) last_visit FROM consumers c LEFT JOIN visits v ON v.consumer_id=c.id AND substr(v.started_server,1,7)=? WHERE c.active=1 GROUP BY c.id ORDER BY c.branch,c.district,c.name LIMIT ? OFFSET ?`).all(mm,limit,off);return send(res,200,{month:mm,page,limit,result:r,has_more:r.length===limit})}
if(req.method==='GET'&&url==='/api/route'){const u=auth(req,res,true);if(!u)return;const p=new URL(req.url,'http://x').searchParams,eid=+(p.get('employee_id')||0),d=dateOk(p.get('date'))?p.get('date'):now().slice(0,10);if(!eid)return send(res,400,{error:'EMPLOYEE_REQUIRED'});return send(res,200,{date:d,employee_id:eid,points:q('SELECT id,ts_server,lat,lon,accuracy,speed FROM gps_points WHERE employee_id=? AND substr(ts_server,1,10)=? ORDER BY ts_server').all(eid,d),visits:q('SELECT v.*,c.name FROM visits v JOIN consumers c ON c.id=v.consumer_id WHERE v.employee_id=? AND substr(v.started_server,1,10)=? ORDER BY v.started_server').all(eid,d)})}
if(req.method==='GET'&&url==='/api/consumer-visits'){const u=auth(req,res,true);if(!u)return;const cid=+new URL(req.url,'http://x').searchParams.get('consumer_id');return send(res,200,{visits:q('SELECT v.*,u.employee_name,u.region,u.district FROM visits v JOIN users u ON u.id=v.employee_id WHERE v.consumer_id=? ORDER BY v.started_server DESC').all(cid)})}
if(req.method==='GET'&&url==='/api/audit'){const u=auth(req,res,true);if(!u)return;const rows=q('SELECT * FROM audit ORDER BY id').all();let prev='GENESIS',valid=true;for(const r of rows){const h=sha([prev,r.ts_server,r.actor_id||'',r.action,r.payload].join('|'));if(r.prev_hash!==prev||r.hash!==h){valid=false;break}prev=r.hash}return send(res,200,{chain_valid:valid,count:rows.length,rows:rows.slice(-100)})}
if(req.method==='GET'&&url==='/api/tasks'){const u=auth(req,res);if(!u)return;const d=new URL(req.url,'http://x').searchParams.get('date');return send(res,200,{date:d||now().slice(0,10),items:tasksFor(u,d)})}
if(req.method==='POST'&&url==='/api/tasks'){const u=auth(req,res,true);if(!u)return;const b=await json(req),title=String(b.title||'').trim(),d=dateOk(b.work_date)?b.work_date:now().slice(0,10),eid=+b.employee_id;if(!title||!eid)return send(res,400,{error:'TASK_REQUIRED'});if(!employee(eid))return send(res,404,{error:'EMPLOYEE_NOT_FOUND'});const r=q('INSERT INTO tasks(title,description,work_date,employee_id,created_by,status,created_at) VALUES(?,?,?,?,?,?,?)').run(title,String(b.description||''),d,eid,u.id,'ASSIGNED',now()),id=+r.lastInsertRowid;for(const f of Array.isArray(b.attachments)?b.attachments:[]){const m=String(f.data||'').match(/^data:([^;]+);base64,(.+)$/s);if(!m)continue;const buf=Buffer.from(m[2],'base64');if(buf.length>6e6)continue;q('INSERT INTO task_files(task_id,uploaded_by,filename,mime,data,uploaded_at) VALUES(?,?,?,?,?,?)').run(id,u.id,fileName(f.name),String(f.type||m[1]),buf,now())}audit(u.id,'TASK_CREATE',{task_id:id,employee_id:eid,work_date:d});return send(res,200,{ok:true,task_id:id})}
const tm=url.match(/^\/api\/tasks\/(\d+)(?:\/files)?$/);if(tm){const id=+tm[1],u=auth(req,res);if(!u)return;const t=q('SELECT t.*,u.employee_name,u.region,u.district FROM tasks t LEFT JOIN users u ON u.id=t.employee_id WHERE t.id=?').get(id);if(!t)return send(res,404,{error:'TASK_NOT_FOUND'});if(u.role!=='admin'&&+t.employee_id!==+u.id)return send(res,403,{error:'TASK_FORBIDDEN'});if(req.method==='GET'&&!url.endsWith('/files'))return send(res,200,{task:t,files:fileRows(id)});if(req.method==='GET'&&url.endsWith('/files')){const f=q('SELECT * FROM task_files WHERE id=? AND task_id=?').get(+new URL(req.url,'http://x').searchParams.get('file'),id);if(!f)return send(res,404,{error:'FILE_NOT_FOUND'});return send(res,200,f.data,f.mime,{'Content-Disposition':`inline; filename="${fileName(f.filename)}"`})}if(req.method==='POST'){const b=await json(req),st=String(b.status||'').toUpperCase();if(!['ASSIGNED','IN_PROGRESS','COMPLETED','NOT_COMPLETED'].includes(st))return send(res,400,{error:'TASK_STATUS_INVALID'});if(u.role!=='admin'&&st==='ASSIGNED')return send(res,403,{error:'TASK_FORBIDDEN'});q('UPDATE tasks SET status=?,result_text=?,completed_at=? WHERE id=?').run(st,String(b.result_text||''),st==='COMPLETED'?now():null,id);for(const f of Array.isArray(b.attachments)?b.attachments:[]){const m=String(f.data||'').match(/^data:([^;]+);base64,(.+)$/s);if(!m)continue;const buf=Buffer.from(m[2],'base64');if(buf.length>6e6)continue;q('INSERT INTO task_files(task_id,uploaded_by,filename,mime,data,uploaded_at) VALUES(?,?,?,?,?,?)').run(id,u.id,fileName(f.name),String(f.type||m[1]),buf,now())}audit(u.id,'TASK_UPDATE',{task_id:id,status:st});return send(res,200,{ok:true})}}
if(req.method==='GET'&&url.startsWith('/api/export/')){const u=auth(req,res,true);if(!u)return;const type=url.split('/').pop().replace('.xls',''),d=now().slice(0,10),rows=type==='consumers'?q('SELECT id,name,region,branch,district,mahalla,street,category,activity,phone,lat,lon FROM consumers WHERE active=1 ORDER BY branch,district,name').all().map(x=>[x.id,x.name,x.region||x.branch,x.district,x.mahalla,x.street,x.category,x.activity,x.phone,x.lat!=null?`${x.lat}, ${x.lon}`:'']):type==='visits'?q('SELECT v.id,u.employee_name,c.name,u.region,u.district,v.started_server,v.ended_server,v.status,v.distance_m,v.outcome,v.notes FROM visits v JOIN users u ON u.id=v.employee_id JOIN consumers c ON c.id=v.consumer_id ORDER BY v.started_server DESC').all().map(x=>[x.id,x.employee_name,x.name,x.region,x.district,x.started_server,x.ended_server||'',x.status,x.distance_m,x.outcome||'',x.notes||'']):q(`SELECT u.employee_name,u.region,u.district,COUNT(a.id) planned,COUNT(v.id) visited FROM users u LEFT JOIN assignments a ON a.employee_id=u.id AND a.work_date=? LEFT JOIN visits v ON v.employee_id=u.id AND v.consumer_id=a.consumer_id AND substr(v.started_server,1,10)=? WHERE u.role='employee' AND u.active=1 GROUP BY u.id ORDER BY u.region,u.district,u.employee_name`).all(d,d).map(x=>[x.employee_name,x.region,x.district,x.planned,x.visited,x.planned?Math.round(x.visited/x.planned*100):0]);const header=type==='consumers'?['ID','Истеъмолчи','Вилоят','Туман/шаҳар','Маҳалла','Манзил','Категория','Фаолият','Телефон','GPS']:type==='visits'?['ID','Ходим','Истеъмолчи','Вилоят','Туман','Кириш','Чиқиш','Ҳолат','Масофа','Натижа','Изоҳ']:['Ходим','Вилоят','Туман','Режа','Ташриф','Бажарилиш %'];const escx=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'),rr=a=>`<Row>${a.map(v=>`<Cell><Data ss:Type="String">${escx(v)}</Data></Cell>`).join('')}</Row>`;return send(res,200,`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Report"><Table>${rr(header)}${rows.map(rr).join('')}</Table></Worksheet></Workbook>`,'application/vnd.ms-excel; charset=utf-8',{'Content-Disposition':`attachment; filename="${type}.xls"`})}
return false}catch(e){console.error('API_ERROR',e);if(!res.headersSent)send(res,500,{error:'SERVER_ERROR',message:String(e.message||e)})}}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return send(res,204,'');const u=new URL(req.url,'http://local'),url=u.pathname;if(url.startsWith('/api/')){const h=await api(req,res,url);if(h!==false)return}if(req.method!=='GET')return send(res,404,{error:'NOT_FOUND'});const p=url==='/'?path.join(__dirname,'public','index.html'):path.join(__dirname,'public',url.slice(1));if(!p.startsWith(path.join(__dirname,'public'))||!fs.existsSync(p))return send(res,404,{error:'NOT_FOUND'});const ext=path.extname(p),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml'};if(ext==='.html'){let html=fs.readFileSync(p,'utf8');if(!html.includes('/tasks-v2.js'))html=html.replace('</body>','<script src="/tasks-v2.js?v=3"></script><script src="/final-ui.js?v=3"></script><script src="/enhance.js?v=3"></script></body>');res.writeHead(200,{'Content-Type':types['.html'],'Cache-Control':'no-store','Content-Length':Buffer.byteLength(html)});return res.end(html)}res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':'no-store'});res.end(fs.readFileSync(p))});server.listen(PORT,'0.0.0.0',()=>console.log(`ULGURJI_SERVER_READY port=${PORT} db=${DB_PATH}`));
